config/routes.rb
Rails.application.routes.draw do
  root to: 'artists#index'

  resources :photo

  resources :artists do
    resources :songs, only: [:create, :destroy]
  end

  namespace :api do
    resources :artists do
      resources :songs
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates :name, presence: true

  has_many :songs, dependent: :destroy
  has_one  :photo, dependent: :destroy
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :artist

  mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist, optional: true

  validates :title, presence: true, length: { maximum: 30}
  validates :year_of_release, presence: true, length: { maximum: 4}
end

app/controllers/api/songs_controller.rb
class Api::SongsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_artist

  def index
    render status: 200, json: {
      songs: @artist.songs
    }.to_json
  end

  def show
    song = Song.find(params[:id])

    render status: 200, json: {
      song: @artist.songs
    }.to_json
  end

  def create
    song = Song.new(song_params.merge(artist_id: params[:artist_id]))

    if song.save
      render status: 201, json: {
        message: "Song added",
        song: @artist.songs
      }.to_json
    else
      render status: 422, json: {
        errors: song.errors
      }.to_json
    end
  end

  def destroy
    song = Song.find(params[:id])
    song.destroy

    render status: 200, json: {
      message: "Song deleted"
    }.to_json
  end

  private

  def song_params
    params.require(:song).permit(:title, :year_of_release)
  end

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
    @photos = @artist.photo
  end

  def destroy
    @artist = Artist.find(params[:id])

    @artist.destroy

    redirect_to artists_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def create
    @song = Song.new(song_params.merge(artist_id: params[:artist_id]))
    if @song.save
    redirect_to artist_path(params[:artist_id])
    else
    redirect_to  @song.artist
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to artist_path(params[:artist_id]) }
      format.js
    end
  end

  private
  def song_params
    params.require(:song).
    permit(:title, :year_of_release, :artist_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/delete_song.js.erb
$("#songs").html("<%= j render 'songs/list' %>");

app/views/artists/index.html.erb
<div class="col-md-9">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h1>Artists</h1>
    </div>


  <% @artists.each do |artist| %>
    <%= image_tag artist.photo.image, :size => "260x280" %>
    <h3><%= link_to artist.name, artist_path(artist.id) %></h3>
  <% end %>

app/views/artists/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1><%= @artist.name %></h1></div>

  <div class="panel-body">
    <% @artist.songs.each do |song| %>
      <h3><%= song.title %></h3>
      <p>Year of release: <%= song.year_of_release %>

      <%= link_to "Delete", artist_song_path(@artist.id, song.id), method: :delete, remote: true, data: { confirm: "Are you sure to delete #{song.title}?"}, class: "btn btn-default-xs" %>

    <% end %>

    <hr>
    <%= render 'songs/form', remote: true %>

</div>

</div>

<%= link_to "Back", artists_path, class: "btn btn-default-xs" %>
<%= link_to "Delete album", artist_path(@artist.id), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-default-xs" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<!-- <h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p> -->

app/views/songs/_form.html.erb
<%= form_for [@artist,@artist.songs.new] do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="form-group">
    <%= f.label :year_of_release %>
    <%= f.number_field :year_of_release %>
  </div>

  <div class="form-group">
    <%= f.submit "Add new song" %>
  </div>

<% end %>